### ISSUE TITLE
Add a new Cypress E2E test runner that executes against a fully configured environment

### ISSUE THREAD

**Issue by NevilleS** [ethyca/fides#1293] opened 2022-10-09 18:22 UTC
### Description

In some previous releases, we worked on building out test setup scripts (#1291) and a local manual test environment (#1292), which gives us the ability to do true E2E manual tests to confirm all features are working as expected when running together.

Our existing Cypress suites for the `admin-ui` and `privacy-center` are great, but they are isolated to their specific applications and tend to stub out their backends for performance. Therefore, there's still an open need for an E2E test runner to use for regression tests on an ongoing basis.

Once the runner is configured, let's put it to work by defining a core smoke test for releases. We should ensure this can run against our local test env first, but I want to immediately start using this against some hosted staging & demo environments in the short-term, so let's ensure that any URLs are easy to configure and override (e.g. http://localhost:3000 will quickly become something like https://fides.fides-staging.ethyca.com/)

In addition, let's signup for Cypress Cloud and publish results there, it's a great product!

### Acceptance Criteria

* MUST implement a new Cypress runner to run E2E tests, targeting the local "manual test" environment (see #1292)
* MUST support targeting different hosts via environment variables, so we can run against staging / demo / etc.
* MUST have a `nox` session (e.g. `nox -s e2e_test`) that runs the Cypress suite in headless mode
* MUST configure the test reporter to publish results to our Cypress Cloud account
* MUST write a single Cypress E2E test that runs a simple smoke test covering:
  1. Confirm can login to the Admin UI
  2. Confirm that the Postgres & Mongo connectors are configured
  3. Confirm that the Privacy Center can be accessed
  4. Submit an access request via the Privacy Center
  5. Approve the access request via the Admin UI
  6. Confirm the access request succeeds

**Comment by ssangervasi** [comment] 2022-10-10 20:05
One note from this convo:
> not running against the live backend in those E2E tests is a bug, not a feature. we’ve scoped out work to fix that here

I am a fan of FE+BE integrated regression test. However, I would say the 80/20 rule for cypress tests is that 80% should be using stubbed endpoints. Developers should be live-running the Cypress tests for a feature when changing it. An actual BE is usually bad for this because:
- It will be slow
- Create/Deletes are going to get out of sync
- The data that is useful for regressions is a separate concern from what is useful for covering a UI feature
- The BE might not even be updated yet (developing features in tandem like Classify UI).

I think this ticket is pointing in the right direction: we should have a distinct subset of test that don't stub anything. I just want to make it clear the goal isn't to convert _all_ cypress tests to run against a live API.

**Comment by NevilleS** [comment] 2023-01-10 14:49
@ssangervasi totally fair - I've updated the title & description here to be more appropriate - you're right that we shouldn't need to replace the existing suites, and in fact an E2E runner is really just one more to add.

**Comment by seanpreston** [comment] 2023-01-26 19:13
Commenting to flag that this work is blocked by https://github.com/ethyca/fides/issues/2385

**Comment by allisonking** [comment] 2023-02-13 21:27
Closed by https://github.com/ethyca/fides/pull/2241

**Closed by allisonking** 2023-02-13 21:27 UTC
Labels: enhancement, Test Automation Improvements
