### ISSUE TITLE
Password in User Management: more explicit instructions

### ISSUE THREAD

**Issue by malaethyca** [ethyca/fides#1530] opened 2022-10-24 09:07 UTC
If you try creating a new user in the admin console under user management: http://localhost:3000/user-management
you will find that you have to play a guessing game to figure what password will be acceptable by the system.

1. Try test1, it will tell you you need a password with eight characters
2. Try test1234, it will tell you that you need a password atleast one capitalized letter
3. Try Test1234, it will tell you that you need a password with atleast one special character
4. Try Test1234# and it will be finally accepted.

Can you imagine what would happen if you forgot what you had typed in last and kept trying different combinations of strings each time instead of building on top of the instructions?

Can we instead just add a note saying Password needs to be eight characters long with atleast one capital letter and a specialized character (and maybe digits?). So that the very first time the user creates the password, they get it right?

**Comment by mfbrown** [comment] 2022-10-26 13:44
Duplicate of https://github.com/ethyca/fidesops/issues/1433

**Closed by mfbrown** 2022-10-26 13:44 UTC
Labels: bug
