### ISSUE TITLE
Build: API that generates dataset for a SaaS application

### ISSUE THREAD

**Issue by malaethyca** [ethyca/fides#1091] opened 2022-09-20 04:45 UTC
Given the endpoint to an API enabled application, automatically generate the dataset config file in Fides Lang.
Arguments of the API: login information to the application
Response of the API: a dataset config in Fides Lang

User Story:
As a connector developer, I want to be able to automatically generate the dataset configuration in Fides Lang, for a given SaaS application.

Note:
This will be used in Fides UI so a non technical user can generate a dataset config.

**Comment by Kelsey-Ethyca** [comment] 2022-11-22 17:07
We did not do this in Phase 1. The functionality exists just not the api. Assigning to @saiatethyca to say whether this is needed or close as not planned.

**Comment by saiatethyca** [comment] 2022-11-29 16:59
This is a duplicate of https://github.com/ethyca/fides-n8n/issues/21

**Closed by saiatethyca** 2022-11-29 16:59 UTC
Labels: SaaS Connector Builder
