### ISSUE TITLE
Celery App Changed Causing Health Check Failures

### ISSUE THREAD

**Issue by RobertKeyser** [ethyca/fides#3625] opened 2023-06-20 18:00 UTC
### Bug Description

For Fides workers, I've been using the health check of `celery --quiet --no-color --app fides.api.tasks inspect ping --destination celery@$HOSTNAME --json`; however, with pre-release versions of Fides (pre-`2.15.0`), I'm getting the following error:

```
Unable to load celery application.
While trying to load the module fides.api.tasks the following error occurred:
Traceback (most recent call last):
  File "/opt/fides/lib/python3.10/site-packages/celery/app/utils.py", line 384, in find_app
    sym = symbol_by_name(app, imp=imp)
  File "/opt/fides/lib/python3.10/site-packages/kombu/utils/imports.py", line 64, in symbol_by_name
    return getattr(module, cls_name) if cls_name else module
AttributeError: module 'fides.api' has no attribute 'tasks'
```

When `2.15.0` is released, the health checks in our released fides-helm chart will break, causing the Fides workers to be continuously restarted.

#### Steps to Reproduce

1. Pull the latest of `main`
2. run `nox -s dev -- shell ui worker`
3. Connect to the worker and run `celery --quiet --no-color --app fides.api.tasks inspect ping --destination celery@$HOSTNAME --json` and receive the error

### Expected behavior

_A description of what you expected to happen._

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Environment

* Version:
* OS:
* Python Version:
* Docker Version:

### Additional context

_Add any other context about the problem here._

**Comment by ThomasLaPiana** [comment] 2023-06-29 15:53
Are we ok to close this issue then? Seems like some kind of weird regression happened that then sorted itself out? Although I'd like to understand why...

**Comment by daveqnet** [comment] 2023-06-30 09:07
I'm happy to to close the issue as can't reproduce - that okay by you, @RobertKeyser?

**Comment by daveqnet** [comment] 2023-08-03 11:10
I'm closing this as can't repro.

**Closed by daveqnet** 2023-08-03 11:10 UTC
Labels: bug

**Comment by Roger-Ethyca** [comment] 2023-08-03 19:40
moving to done
