### ISSUE TITLE
Errors when Database or Cache become Unavailable

### ISSUE THREAD

**Issue by RobertKeyser** [ethyca/fides#2034] opened 2022-12-13 16:42 UTC
### Bug Description

My Fides pods died this morning, so I checked the logs and found the following errors.

```
Traceback (most recent call last):
  File "/root/.local/lib/python3.10/site-packages/starlette/middleware/base.py", line 43, in call_next
    message = await recv_stream.receive()
  File "/root/.local/lib/python3.10/site-packages/anyio/streams/memory.py", line 114, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.local/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 372, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/root/.local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/root/.local/lib/python3.10/site-packages/fastapi/applications.py", line 269, in __call__
    await super().__call__(scope, receive, send)
  File "/root/.local/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/root/.local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/root/.local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/root/.local/lib/python3.10/site-packages/starlette/middleware/base.py", line 68, in __call__
    response = await self.dispatch_func(request, call_next)
  File "/usr/local/lib/python3.10/site-packages/fides/api/main.py", line 276, in log_request
    response = await call_next(request)
  File "/root/.local/lib/python3.10/site-packages/starlette/middleware/base.py", line 46, in call_next
    raise app_exc
  File "/root/.local/lib/python3.10/site-packages/starlette/middleware/base.py", line 36, in coro
    await self.app(scope, request.receive, send_stream.send)
  File "/root/.local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/root/.local/lib/python3.10/site-packages/starlette/middleware/base.py", line 68, in __call__
    response = await self.dispatch_func(request, call_next)
  File "/usr/local/lib/python3.10/site-packages/fides/api/main.py", line 107, in dispatch_log_request
    return await call_next(request)
  File "/root/.local/lib/python3.10/site-packages/starlette/middleware/base.py", line 46, in call_next
    raise app_exc
  File "/root/.local/lib/python3.10/site-packages/starlette/middleware/base.py", line 36, in coro
    await self.app(scope, request.receive, send_stream.send)
  File "/root/.local/lib/python3.10/site-packages/starlette/middleware/base.py", line 68, in __call__
    response = await self.dispatch_func(request, call_next)
  File "/root/.local/lib/python3.10/site-packages/slowapi/middleware.py", line 54, in dispatch
    return exception_handler(request, e)
  File "/root/.local/lib/python3.10/site-packages/slowapi/extension.py", line 88, in _rate_limit_exceeded_handler
    {"error": f"Rate limit exceeded: {exc.detail}"}, status_code=429
AttributeError: 'ConnectionError' object has no attribute 'detail'
ERROR:uvicorn.error:Exception in ASGI application
Traceback (most recent call last):
  File "/root/.local/lib/python3.10/site-packages/anyio/streams/memory.py", line 94, in receive
    return self.receive_nowait()
  File "/root/.local/lib/python3.10/site-packages/anyio/streams/memory.py", line 89, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.local/lib/python3.10/site-packages/starlette/middleware/base.py", line 43, in call_next
    message = await recv_stream.receive()
  File "/root/.local/lib/python3.10/site-packages/anyio/streams/memory.py", line 114, in receive
    raise EndOfStream
anyio.EndOfStream
```

Upon first glance, I thought this error was related to how we're handling rate limits, given the `{"error": f"Rate limit exceeded: {exc.detail}"}, status_code=429` and `AttributeError: 'ConnectionError' object has no attribute 'detail'`; however, after chatting with @adamsachs, it seems like this might also be related to the server's inability to reach either Redis or Postgres. I took a look at my Redis and Postgres pods and sure enough, they were down too.

#### Steps to Reproduce

Not exactly sure, but try taking down your redis and postgres instances on a working Fides server.

### Expected behavior

I would expect health checks to fail for the webserver and an error that explicitly calls out the loss of connectivity to the databases.

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Environment

* Version: `ethyca/fides:dev`, specifically the following hash: `d3ab98ac526a558257010fcd159a95cf513d44f4e8a8ad29949145012ee875be`

Running on Kubernetes on EKS.

### Additional context

_Add any other context about the problem here._

**Comment by adamsachs** [comment] 2022-12-13 21:59
noting here i'm able to reproduce this in local testing, and it this seems to be specifically tied to the redis cache going down. i think i've pinned it down to the fact that our rate limiter uses our redis cache as a backend (https://github.com/ethyca/fides/blob/main/src/fides/api/main.py#L81), which seems like it should be fully supported by `slowapi` -- https://slowapi.readthedocs.io/en/latest/examples/#use-redis-as-backend-for-the-limiter and https://limits.readthedocs.io/en/stable/storage.html#id3 (`limits` is `slowapi`'s storage library).

the error here seems to be fully within `slowapi`'s code, i.e. it's choking on a `ConnectionError` that is seemingly coming back when the redis cache is down. this seems like a pretty basic error state that the library should be able to handle, so perhaps we're doing something wrong in our implementation - that needs further investigation. 

regardless, we should do everything we can to make this state clearer to the end user, since our app pretty much becomes unusable once the redis cache is down, and it's _very_ difficult to debug (even the logging fixes in https://github.com/ethyca/fides/pull/2031 don't help us here 🙃 )

**Comment by adamsachs** [comment] 2022-12-16 02:39
this should be fixed as part of https://github.com/ethyca/fides/pull/2058

**Closed by adamsachs** 2022-12-16 02:39 UTC
Labels: bug

**Comment by ewdurbin** [comment] 2023-06-04 22:43
Experiencing this running on latest commit:

```
fides-admin-web-644c7bf6f4-4bjbv web Exception in ASGI application
fides-admin-web-644c7bf6f4-4bjbv web Traceback (most recent call last):
fides-admin-web-644c7bf6f4-4bjbv web   File "/opt/fides/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 435, in run_asgi
fides-admin-web-644c7bf6f4-4bjbv web     result = await app(  # type: ignore[func-returns-value]
fides-admin-web-644c7bf6f4-4bjbv web   File "/opt/fides/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
fides-admin-web-644c7bf6f4-4bjbv web     return await self.app(scope, receive, send)
fides-admin-web-644c7bf6f4-4bjbv web   File "/opt/fides/lib/python3.10/site-packages/fastapi/applications.py", line 270, in __call__
fides-admin-web-644c7bf6f4-4bjbv web     await super().__call__(scope, receive, send)
fides-admin-web-644c7bf6f4-4bjbv web   File "/opt/fides/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__
fides-admin-web-644c7bf6f4-4bjbv web     await self.middleware_stack(scope, receive, send)
fides-admin-web-644c7bf6f4-4bjbv web   File "/opt/fides/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
fides-admin-web-644c7bf6f4-4bjbv web     raise exc
fides-admin-web-644c7bf6f4-4bjbv web   File "/opt/fides/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
fides-admin-web-644c7bf6f4-4bjbv web     await self.app(scope, receive, _send)
fides-admin-web-644c7bf6f4-4bjbv web   File "/opt/fides/lib/python3.10/site-packages/starlette/middleware/base.py", line 106, in __call__
fides-admin-web-644c7bf6f4-4bjbv web     response = await self.dispatch_func(request, call_next)
fides-admin-web-644c7bf6f4-4bjbv web   File "/opt/fides/lib/python3.10/site-packages/slowapi/middleware.py", line 130, in dispatch
fides-admin-web-644c7bf6f4-4bjbv web     error_response, should_inject_headers = sync_check_limits(
fides-admin-web-644c7bf6f4-4bjbv web   File "/opt/fides/lib/python3.10/site-packages/slowapi/middleware.py", line 77, in sync_check_limits
fides-admin-web-644c7bf6f4-4bjbv web     return exception_handler(request, exc), _bool  # type: ignore
fides-admin-web-644c7bf6f4-4bjbv web   File "/opt/fides/lib/python3.10/site-packages/slowapi/extension.py", line 82, in _rate_limit_exceeded_handler
fides-admin-web-644c7bf6f4-4bjbv web     {"error": f"Rate limit exceeded: {exc.detail}"}, status_code=429
fides-admin-web-644c7bf6f4-4bjbv web AttributeError: 'AttributeError' object has no attribute 'detail'
```

**Comment by adamsachs** [comment] 2023-06-04 23:24
hi @ewdurbin, thanks for reporting! would you be able to provide a bit more detail on your setup, or any specific steps you've taken that has gotten your server into that error state?

i'm running my server locally on latest `main` and so far i haven't been able to reproduce using the steps that were responsible in this issue initially; i.e., killing the redis and/or postgres services that `fides` is hooked up to. locally, when i:
1. start `fides` alongside a redis and postgres container using `nox -s dev`
2. kill my redis and postgres containers (`docker kill fides-fides-db-1 fides-redis-1`)
i see the following errors in the `fides` server logs, which is expected:
```
fides  | 2023-06-04 23:18:39.220 [ERROR] (database:get_db_health:100): Unable to reach the database: sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "fides-db" to address: Name or service not known
fides  |
fides  | (Background on this error at: https://sqlalche.me/e/14/e3q8)
fides  | 2023-06-04 23:18:39.220 [DEBUG] (cache:get_cache:178): Testing Redis connection...
fides  | 2023-06-04 23:18:39.228 [DEBUG] (cache:get_cache:187): Redis connection failed.
fides  | 2023-06-04 23:18:39.229 [ERROR] (health:get_cache_health:43): Unable to reach cache: Unable to establish Redis connection. Fidesops is unable to accept PrivacyRequsts.
fides  | 2023-06-04 23:18:39.230 [INFO] (main:log_request:139): Request received | {'method': 'GET', 'status_code': 503, 'handler_time': '21.717ms', 'path': '/health'}
```
but generally `fides` stays "healthy" in that it continues to respond to the basic `/health` endpoint (although app functionality will be severely curtailed in this state, as is to be expected!).

that being said, there have been some relatively recent changes to the server's rate limiting, so perhaps there's been some change in behavior that's causing the problem for you. on my end, i'll just need a few more details to be able to better pinpoint the problem, as i haven't been able to reproduce it!

**Comment by ewdurbin** [comment] 2023-06-04 23:27
looks like it _may_ have been that I'm running this via:

```
uvicorn fides.api.app_setup:create_fides_app --uds /var/run/cabotage/cabotage.sock --log-level debug
```

(to bind to a unix domain socket rather than a TCP port, per policy of the environment I run in)

rather than

```
uvicorn fides.api.main:app --uds /var/run/cabotage/cabotage.sock --log-level debug
```

So I guess its something to do with the imports that happen by importing the app via fides.api.main rather than fides.api.app_setup

**Comment by ewdurbin** [comment] 2023-06-04 23:34
Confirming that was it. For reasons that are unclear to me, getting the app from `fides.api.main:app` gets over this hurdle... but getting a new error trying to connect over unix domain socket.

**Comment by ThomasLaPiana** [comment] 2023-06-06 15:08
@ewdurbin this was solved by the `SlowAPI` version bump right?

**Comment by ewdurbin** [comment] 2023-06-06 15:21
Confirmed. Thank you.
