### ISSUE TITLE
Reveal PII preference persists across pages

### ISSUE THREAD

**Issue by seanpreston** [ethyca/fides#1926] opened 2022-08-05 19:48 UTC
## Replication steps
- Load the subject request dashboard
- Toggle reveal PII on
- Navigate to a subject request details page
- Notice that the PII is still revealed, despite the toggle for this page being off

Please note: this also replicates by toggling reveal PII on in the detail view and then navigating back to the dashboard

**Comment by saiatethyca** [comment] 2023-01-20 17:26
Duplicate of https://github.com/ethyca/fides/issues/2286

**Comment by NevilleS** [comment] 2023-01-25 20:05
Duplicate of #2286

**Closed by NevilleS** 2023-01-25 20:05 UTC
Labels: bug
