### ISSUE TITLE
Add data categories from associated system datasets to system and data map table

### ISSUE THREAD

**Issue by rsilvery** [ethyca/fides#3866] opened 2023-07-27 15:35 UTC
When we updated the data map table and data use declarations, we broke the functionality wherein data categories that exist in datasets that are associated with a system appear in the data map table export. Example flow:
- Customer creates a dataset and annotates it with categories
- Customer associates this dataset with a system
- Categories appear in the data map table (broken).

The solution is to create a catch all data use with a title like default or unassigned and nest the unassigned categories (and cookies) . We already did a design for this that can be seen [here](https://www.figma.com/file/dmEwdK3xZwjKfGVQ9t66xe/Fides-v.2-Master-Working-Files?type=design&node-id=7480%3A120369&mode=design&t=vKsHIc9agdqcq5le-1)

**Comment by rsilvery** [comment] 2023-08-08 15:55
@TheAndrewJackson  just to confirm from a conversation we had with @NevilleS  and @pattisdr  today: we're going to keep the dataset reference field in the data use declaration. 
So, we need to make sure this is fixed for that case.

**Comment by rsilvery** [comment] 2023-08-08 16:00
Then, additionally, we need a dataset references field in the system -level as in the designs. The data categories that are annotated in that dataset should appear in this new catch-all data use.

**Comment by TheAndrewJackson** [comment] 2023-08-08 18:38
@Roger-Ethyca I was unable to reproduce this issue and I reviewed that it was working as indented using fidesplus main with @rsilvery. Can you test this with the most recent release?

**Comment by Roger-Ethyca** [comment] 2023-08-16 20:33
moving to done

**Closed** 2023-08-28 21:43 UTC
