### ISSUE TITLE
No create new connection button

### ISSUE THREAD

**Issue by azazeldt** [ethyca/fides#1163] opened 2022-09-30 20:21 UTC
### Bug Description

No create new connection button

#### Steps to Reproduce

1. On a fresh install of the UI 
2. Spin everything up and log in
3. Navigate to the tab datastore connection 

### Expected behavior

Button should be available 

### Screenshots

![image](https://user-images.githubusercontent.com/7914716/193350307-e981a538-dd87-4a37-963f-d0b4b10c6ff8.png)

### Environment

* Version:
* OS:
* Python Version:
* Docker Version:

### Additional context

_Add any other context about the problem here._

**Comment by NevilleS** [comment] 2022-10-03 19:55
Assigning this one to @TheAndrewJackson: I think I might see the root cause here from poking around elsewhere...

It looks like the `flag.json` file in the merged UI might have the wrong commit history. It showing that it was renamed like so:
`clients/ctl/admin-ui/src/mocks/browser.ts` -> `clients/admin-ui/src/flags.json`

(see https://github.com/ethyca/fides/commits/unified-fides-2/clients/admin-ui/src/flags.json)

Whereas I'd expect this to have been moved from:
`clients/ops/admin-ui/src/flags.json` -> `clients/admin-ui/src/flags.json`

(see https://github.com/ethyca/fides/commits/unified-fides-2/clients/ops/admin-ui/src/flags.json)

**Comment by NevilleS** [comment] 2022-10-04 18:45
@TheAndrewJackson I think I see the issue here - it's not related to unified, it's a different problem. It looks like the "empty state" for this page isn't rendering like we expect, which prevents showing the button.

**Comment by TheAndrewJackson** [comment] 2022-10-05 15:04
@NevilleS This may have been fixed after merging 1.8.1 in yesterday. This is what I see after running the updated admin ui. 

![Screen Shot 2022-10-05 at 10 59 49](https://user-images.githubusercontent.com/17103888/194094242-396fa0c0-90f9-4238-b640-a1e59b835028.png)


![Screen Shot 2022-10-05 at 11 00 48](https://user-images.githubusercontent.com/17103888/194094307-99e3862e-7aac-41af-ac56-762c8945a6e0.png)

Do you see it working with the newest version as well?

**Comment by NevilleS** [comment] 2022-10-07 16:32
Yes, confirmed that this is working now! Thanks for checking 👍

**Closed by NevilleS** 2022-10-07 16:32 UTC
Labels: bug
